### ISSUE TITLE
Cannot find module './impl/format' in 15.9.8

### ISSUE THREAD

**Issue by kconner** [ryoppippi/ccusage#536]
I typically use `npx ccusage` with various arguments. This worked fine earlier today, but since updating to 15.9.8, I get a crash on launch.

Workaround: `npx ccusage@15.9.7`

```sh
$ npx ccusage
Need to install the following packages:
ccusage@15.9.8
Ok to proceed? (y) 

node:internal/modules/cjs/loader:1401
  const err = new Error(message);
              ^

Error: Cannot find module './impl/format'
Require stack:
- /Users/<user>/.npm/_npx/5032fdcfd7bcf20e/node_modules/ccusage/dist/pricing-fetcher-s0HJ9Lpa.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at file:///Users/<user>/.npm/_npx/5032fdcfd7bcf20e/node_modules/ccusage/dist/index.js:4261:23
    at file:///Users/<user>/.npm/_npx/5032fdcfd7bcf20e/node_modules/ccusage/dist/index.js:4249:12 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/<user>/.npm/_npx/5032fdcfd7bcf20e/node_modules/ccusage/dist/pricing-fetcher-s0HJ9Lpa.js'
  ]
}

Node.js v22.17.1
```

(macOS 15.6)

**Comment by mattharvill** [comment]
I'm getting similar: ""Module not found error './impl/format' with Node.js v22.18.0""
**Environment:**
- Node.js version: v22.18.0
- OS: Ubuntu (WSL)
- ccusage version: 15.9.8 (latest)
- 
Error: Cannot find module './impl/format'
Require stack: /home/abc/.nvm/versions/node/v22.18.0/lib/node_modules/ccusage/dist/pricing-fetcher-s0HJ9Lpa.js

- Also tried with `npx ccusage@latest` and `bunx ccusage` - same error
- Error suggests missing dependency in the bundled distribution

**Comment by gAdrev** [comment]
confirm, same error as OP

```
$ node --version
v20.18.3
$ lsb_release -a  
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.10
Release:	24.10
Codename:	oracular
```

`npx ccusage@15.9.7` works correctly.

**Comment by ryoppippi** [comment]
thank you so much

**Comment by mertdeveci5** [comment]
same issue with me

**Comment by ryoppippi** [comment]
fixed!

try 15.9.9

**Comment by ryoppippi** [comment]
thanks
the reason is because of https://www.npmjs.com/package/jsonc-parser is accidentally bundled.
I removed jsonc support from my library https://github.com/ryoppippi/limo and now it must work fine

**Comment by ryoppippi** [comment]
i also realised so many ppl using ccusage.
i published it within 2 hours and 20 👍🏼 !?!? no way.
Thank you for loving ccusage guys!!

<img width="336" height="115" alt="Image" src="https://github.com/user-attachments/assets/bd536bc9-2fda-4d7a-9b99-19e3ed266fd1" />

**Comment by ryoppippi** [comment]
hey guys, how the latest one

**Comment by ryoppippi** [comment]
tell me when it works.
I'll go back to my dinner!!!

**Comment by isometry** [comment]
15.9.9 is working :-)

**Comment by ryoppippi** [comment]
🥳

**Comment by mattharvill** [comment]
It's working, major props! thanks for the quick turnaround time too!
